[package]
name = "axiom"
version = "0.1.0"
edition = "2021"
authors = ["Axiom Contributors"]
description = "A hybrid Wayland compositor combining scrollable workspaces with beautiful visual effects"
repository = "https://github.com/axiom-wm/axiom"
license = "GPL-3.0"
keywords = ["wayland", "compositor", "window-manager", "tiling", "effects"]
categories = ["gui"]

[dependencies]
# Configuration and serialization
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
clap = { version = "4.4", features = ["derive"] }

# Async runtime and utilities  
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"
env_logger = "0.10"

# Core Wayland compositor dependencies
wayland-server = "0.31"
wayland-protocols = { version = "0.31", features = ["server", "staging"] }
# Smithay compositor framework with available features
smithay = { version = "0.3.0", features = [
    "backend_winit", 
    "renderer_gl",
    "wayland_frontend"
] }
glium = "0.34"
cgmath = "0.18"
xkbcommon = "0.7"
libc = "0.2"
calloop = "0.12"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Graphics and rendering
wgpu = "0.19"
winit = "0.29"

# IPC for Lazy UI integration
serde_json = "1.0"
interprocess = "1.2"  # For Unix socket communication
dbus = "0.9"  # Alternative IPC method

# Utilities
rand = "0.8"  # For input simulation in Phase 3
bytemuck = { version = "1.14", features = ["derive"] }  # For GPU buffer data

# TODO: Add features when compositor dependencies are ready
# [features]
# default = ["smithay-backend"]
# smithay-backend = ["smithay"]
# wlroots-backend = ["wlroots-rs"]

# Development dependencies
[dev-dependencies]
criterion = "0.5"

# Build optimizations
[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 1  # Faster compilation during development

# Workspace configuration for future modules
[workspace]
members = [
    ".",
    # Future: separate crates for effects, workspace management, etc.
]
