[package]
name = "axiom"
version = "0.1.0"
edition = "2021"
authors = ["Axiom Contributors"]
description = "A hybrid Wayland compositor combining scrollable workspaces with beautiful visual effects"
repository = "https://github.com/GeneticxCln/axiom"
license = "GPL-3.0"
keywords = ["wayland", "compositor", "window-manager", "tiling", "effects"]
categories = ["gui"]
autobins = false
default-run = "axiom-compositor"

[[bin]]
name = "axiom-compositor"
path = "src/main.rs"

[[bin]]
name = "run_minimal_wayland"
path = "src/bin/run_minimal_wayland.rs"
required-features = ["smithay-minimal"]

[[bin]]
name = "run_present_winit"
path = "src/bin/run_present_winit.rs"
required-features = ["smithay", "wgpu-present"]

[[bin]]
name = "test_basic"
path = "src/test_basic.rs"
required-features = ["demo"]
test = false

# Gate examples by a feature so they don't break default builds/tests
[[example]]
name = "metrics_client"
path = "examples/metrics_client.rs"
required-features = ["examples"]

[[bin]]
name = "test_socket"
path = "src/test_socket.rs"
required-features = ["demo"]
test = false

[dependencies]
# Configuration and serialization
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
clap = { version = "4.4", features = ["derive"] }

# Async runtime and utilities  
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"
env_logger = "0.10"

# Core Wayland compositor dependencies
wayland-server = "0.31"
wayland-protocols = { version = "0.31", features = ["server", "staging", "unstable"] }
wayland-protocols-wlr = { version = "0.2", features = ["server"] }
wayland-backend = "0.3"
wayland-scanner = "0.31"

# Smithay compositor framework with full features
smithay = { version = "0.7.0", default-features = false, optional = true }
smithay-client-toolkit = "0.18"

# Graphics and input
cgmath = "0.18"
xkbcommon = "0.7"
libc = "0.2"
calloop = "0.12"
calloop-wayland-source = "0.2"
input = "0.9"
evdev = "0.12"
udev = "0.8"
drm = "0.11"
gbm = "0.14"
memmap2 = "0.9"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Graphics and rendering
wgpu = "0.19"
pollster = { version = "0.3", optional = true }
winit = "0.29"

# IPC for Lazy UI integration
serde_json = "1.0"
interprocess = "1.2"  # For Unix socket communication
dbus = "0.9"  # Alternative IPC method
ctrlc = "3.4"  # For graceful shutdown

# Utilities
rand = "0.8"  # For input simulation in Phase 3
bytemuck = { version = "1.14", features = ["derive"] }  # For GPU buffer data
parking_lot = "0.12"  # For RwLock synchronization
nvml-wrapper = { version = "0.10", optional = true }
# Vulkan bindings for dmabuf import (feature-gated)
ash = { version = "0.38", default-features = false, optional = true }
libloading = { version = "0.8", optional = true }

# For server-side cursor rendering
tiny-skia = "0.11"

# For visual testing and golden image support
png = "0.17"

# TODO: Add features when compositor dependencies are ready
# [features]
# default = ["smithay-backend"]
# smithay-backend = ["smithay"]
# wlroots-backend = ["wlroots-rs"]

# Library configuration
[lib]
name = "axiom"
path = "src/lib.rs"


# Features
[features]
# Production defaults: Smithay backend with on-screen presentation
default = ["smithay", "smithay-minimal", "wgpu-present"]

# Base smithay dependency with minimal protocol frontend
smithay = ["dep:smithay", "smithay/wayland_frontend"]

# Smithay-minimal is an alias for smithay (maintained for compatibility)
smithay-minimal = ["smithay"]

# Full smithay backend capabilities (DRM, udev, libinput, xwayland, GL rendering)
smithay-full = [
    "smithay",
    "smithay/backend_winit",
    "smithay/backend_drm",
    "smithay/backend_libinput",
    "smithay/backend_session",
    "smithay/backend_udev",
    "smithay/renderer_gl",
    "smithay/xwayland"
]

# Enable on-screen presentation via wgpu + winit
wgpu-present = ["pollster"]

# Enable NVIDIA NVML GPU metrics support (requires libnvidia-ml)
# Usage: cargo build --features gpu-nvml
gpu-nvml = ["nvml-wrapper"]

# Vulkan-based dmabuf import for zero-copy GPU buffer sharing
# Usage: cargo build --features dmabuf-vulkan
dmabuf-vulkan = ["dep:ash", "dep:libloading"]

# Demo and example features (no-op gates for test/example binaries)
demo = []
examples = []

# Debug effects logging (disabled in release for performance)
debug-effects = []

# Development dependencies for testing
[dev-dependencies]
criterion = "0.5"
# Unit testing frameworks
 tokio-test = "0.4"
 mockall = "0.12"  # For mocking
 proptest = "1.4"  # Property-based testing
 quickcheck = "1.0"  # QuickCheck-style testing
 # Integration testing utilities
 tempfile = "3.0"  # Temporary files and directories for tests
 serial_test = "3.0"  # Sequential test execution
 # Async testing utilities
 futures-test = "0.3"
 # Wayland client for connectivity tests (used only when feature `real-compositor` is enabled)
 wayland-client = "0.31"

[build-dependencies]
chrono = { version = "0.4", features = ["serde"] }

# Build optimizations
[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 1  # Faster compilation during development

# Workspace configuration for future modules
[workspace]
members = [
    ".",
    # Future: separate crates for effects, workspace management, etc.
]
