[package]
name = "axiom"
version = "0.1.0"
edition = "2021"
authors = ["Axiom Contributors"]
description = "A hybrid Wayland compositor combining scrollable workspaces with beautiful visual effects"
repository = "https://github.com/GeneticxCln/axiom"
license = "GPL-3.0"
keywords = ["wayland", "compositor", "window-manager", "tiling", "effects"]
categories = ["gui"]

[[bin]]
name = "axiom"
path = "src/main.rs"

[[bin]]
name = "test_real_backend"
path = "src/test_real_backend.rs"
required-features = ["real-compositor", "experimental-smithay"]
test = false

[[bin]]
name = "test_basic"
path = "src/test_basic.rs"
required-features = ["demo"]
test = false

# Gate examples by a feature so they don't break default builds/tests
[[example]]
name = "metrics_client"
path = "examples/metrics_client.rs"
required-features = ["examples"]

[[bin]]
name = "test_socket"
path = "src/test_socket.rs"
required-features = ["demo"]
test = false

[[bin]]
name = "test_real"
path = "src/test_real.rs"
required-features = ["real-compositor", "experimental-smithay"]
test = false

[[bin]]
name = "run_real_backend"
path = "src/bin/run_real_backend.rs"
required-features = ["real-compositor", "experimental-smithay"]
test = false

[dependencies]
# Configuration and serialization
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
clap = { version = "4.4", features = ["derive"] }

# Async runtime and utilities  
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"
env_logger = "0.10"

# Core Wayland compositor dependencies
wayland-server = "0.31"
wayland-protocols = { version = "0.31", features = ["server", "staging", "unstable"] }
wayland-backend = "0.3"
wayland-scanner = "0.31"

# Smithay compositor framework with full features
smithay = { version = "0.3.0", default-features = false, features = [
    "backend_winit",
    "backend_drm",
    "backend_libinput", 
    "backend_session",
    "backend_udev",
    "renderer_gl",
    "wayland_frontend",
    "xwayland"
] }
smithay-client-toolkit = "0.18"

# Graphics and input
glium = "0.34"
cgmath = "0.18"
xkbcommon = "0.7"
libc = "0.2"
calloop = "0.12"
input = "0.9"
drm = "0.11"
gbm = "0.14"
gl = "0.14"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Graphics and rendering
wgpu = "0.19"
winit = "0.29"

# IPC for Lazy UI integration
serde_json = "1.0"
interprocess = "1.2"  # For Unix socket communication
dbus = "0.9"  # Alternative IPC method
ctrlc = "3.4"  # For graceful shutdown

# Utilities
rand = "0.8"  # For input simulation in Phase 3
bytemuck = { version = "1.14", features = ["derive"] }  # For GPU buffer data
parking_lot = "0.12"  # For RwLock synchronization

# TODO: Add features when compositor dependencies are ready
# [features]
# default = ["smithay-backend"]
# smithay-backend = ["smithay"]
# wlroots-backend = ["wlroots-rs"]

# Library configuration
[lib]
name = "axiom"
path = "src/lib.rs"


# Features
[features]
default = []
demo = []
real-compositor = []
wgpu-present = []
examples = []
experimental-smithay = []

# Development dependencies for testing
[dev-dependencies]
criterion = "0.5"
# Unit testing frameworks
tokio-test = "0.4"
mockall = "0.12"  # For mocking
proptest = "1.4"  # Property-based testing
quickcheck = "1.0"  # QuickCheck-style testing
# Integration testing utilities
tempfile = "3.0"  # Temporary files and directories for tests
serial_test = "3.0"  # Sequential test execution
# Async testing utilities
futures-test = "0.3"

[build-dependencies]
chrono = { version = "0.4", features = ["serde"] }

# Build optimizations
[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 1  # Faster compilation during development

# Workspace configuration for future modules
[workspace]
members = [
    ".",
    # Future: separate crates for effects, workspace management, etc.
]
