#!/usr/bin/env bash
# Axiom alpha release preparation helper.
#
# This script is intentionally conservative: it prepares release notes and
# prints the publish commands, but it does NOT create tags or GitHub releases
# on its own. That keeps the repository's release workflow explicit and honest.

set -euo pipefail

MODE="${1:-help}"
ARG_TAG="${2:-}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
CARGO_TOML="$PROJECT_ROOT/Cargo.toml"
CHECKLIST="$PROJECT_ROOT/docs/dev/RELEASE_CHECKLIST.md"
LIMITATIONS_DOC="$PROJECT_ROOT/docs/user/LIMITATIONS.md"
PROCESS_DOC="$PROJECT_ROOT/docs/dev/RELEASE_PROCESS.md"
NOTES_TEMPLATE="$PROJECT_ROOT/docs/dev/RELEASE_NOTES_TEMPLATE.md"
NOTES_DIR="$PROJECT_ROOT/release-notes"
ALLOW_DIRTY="${AXIOM_RELEASE_ALLOW_DIRTY:-false}"

log() {
    echo "[release-prep] $*"
}

fail() {
    echo "[release-prep] ERROR: $*" >&2
    exit 1
}

usage() {
    cat <<EOF
Axiom alpha release preparation helper

Usage:
  $0 check [tag]
  $0 draft-notes [tag]
  $0 print-publish [tag]
  $0 all [tag]
  $0 help

Modes:
  check          Validate repository release-prep prerequisites
  draft-notes    Generate a draft release-notes markdown file
  print-publish  Print the git/gh commands to create a draft release
  all            Run check, generate notes, and print publish commands
  help           Show this help text

Arguments:
  tag            Optional release tag (default: v<crate-version>-alpha.1)

Environment:
  AXIOM_RELEASE_ALLOW_DIRTY=true   Allow check mode to pass with a dirty git tree
EOF
}

require_tool() {
    local tool="$1"
    command -v "$tool" >/dev/null 2>&1 || fail "required tool missing: $tool"
}

crate_version() {
    awk -F ' = ' '/^version = / { gsub(/"/, "", $2); print $2; exit }' "$CARGO_TOML"
}

default_tag() {
    local version
    version="$(crate_version)"
    [[ -n "$version" ]] || fail "failed to extract crate version from Cargo.toml"
    printf 'v%s-alpha.1' "$version"
}

release_tag() {
    if [[ -n "$ARG_TAG" ]]; then
        printf '%s' "$ARG_TAG"
    else
        default_tag
    fi
}

notes_path() {
    local tag="$1"
    printf '%s/%s.md' "$NOTES_DIR" "$tag"
}

check_repo_state() {
    require_tool git

    [[ -f "$CARGO_TOML" ]] || fail "missing Cargo.toml"
    [[ -f "$CHECKLIST" ]] || fail "missing release checklist: $CHECKLIST"
    [[ -f "$LIMITATIONS_DOC" ]] || fail "missing limitations doc: $LIMITATIONS_DOC"
    [[ -f "$PROCESS_DOC" ]] || fail "missing release process doc: $PROCESS_DOC"
    [[ -f "$NOTES_TEMPLATE" ]] || fail "missing release notes template: $NOTES_TEMPLATE"

    local version
    version="$(crate_version)"
    [[ -n "$version" ]] || fail "crate version is empty"

    if ! git diff --quiet || ! git diff --cached --quiet; then
        if [[ "$ALLOW_DIRTY" == "true" ]]; then
            log "Dirty git tree allowed by AXIOM_RELEASE_ALLOW_DIRTY=true"
        else
            fail "git working tree is dirty; commit or stash changes before release prep"
        fi
    fi

    local current_branch
    current_branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
    log "Release prep check passed on branch: $current_branch"
    log "Crate version: $version"
    log "Suggested tag: $(release_tag)"
}

generate_notes() {
    local tag="$1"
    local version
    version="$(crate_version)"
    mkdir -p "$NOTES_DIR"
    local out
    out="$(notes_path "$tag")"

    cp "$NOTES_TEMPLATE" "$out"

    python3 - <<PY
from pathlib import Path
path = Path(r'''$out''')
text = path.read_text()
text = text.replace('vX.Y.Z-alpha.N', '$tag')
text = text.replace('Axiom vX.Y.Z-alpha.N', 'Axiom $tag')
path.write_text(text)
PY

    cat <<EOF >> "$out"

---

Generated by: scripts/release_prep.sh
Crate version: ${version}
Suggested tag: ${tag}
EOF

    log "Draft release notes written to: $out"
}

print_publish_commands() {
    local tag="$1"
    local notes
    notes="$(notes_path "$tag")"

    cat <<EOF
# Review and edit the generated release notes first:
${notes}

# Then create and push the release tag:
git tag -a ${tag} -m "Axiom ${tag}"
git push origin ${tag}

# Then create a draft GitHub release from the tag:
gh release create ${tag} \
  --draft \
  --title "Axiom ${tag}" \
  --notes-file "${notes}"
EOF
}

case "$MODE" in
    check)
        check_repo_state
        ;;
    draft-notes)
        generate_notes "$(release_tag)"
        ;;
    print-publish)
        print_publish_commands "$(release_tag)"
        ;;
    all)
        check_repo_state
        generate_notes "$(release_tag)"
        print_publish_commands "$(release_tag)"
        ;;
    help|-h|--help)
        usage
        ;;
    *)
        fail "unknown mode: $MODE (try: $0 help)"
        ;;
esac
